image: tiangolo/docker-with-compose

services:
  - docker:dind

stages:
  - test

before_script:
  - curl -s https://storage.googleapis.com/golang/go1.2.2.linux-amd64.tar.gz| tar -v -C /usr/local -xz
  - /usr/local/go/bin/go run utils/main.go

format:
  stage: test
  variables:
    LOADBALANCER_PORT: 8081
  script:
    - docker-compose build
    - docker-compose up -d
    - docker-compose exec -T loadbalancer go test ./...
    - docker-compose exec -T supervisor go test ./...
    - docker-compose down -v
