image: tiangolo/docker-with-compose

services:
  - docker:dind

stages:
  - test

format:
  stage: test
  variables:
    LOADBALANCER_PORT: 8081
  script:
    - docker-compose build
    - docker-compose up -d
    - docker-compose exec -T loadbalancer go test ./...
    - docker-compose exec -T supervisor go test ./...
    - docker-compose down -v
  only:
    - develop
