image: tiangolo/docker-with-compose

services:
  - docker:dind

stages:
  - test

before_script:
  - apk add go 
  - go run utils/main.go

run tests and build app:
  stage: test
  script:
    - docker-compose build
    - docker-compose up -d
    - docker-compose exec -T loadbalancer go test ./...
    - docker-compose exec -T supervisor go test ./...
    - docker-compose exec -T storage go test ./...
    - docker-compose down -v
  only:
    - develop
