image: tiangolo/docker-with-compose

services:
  - docker:dind

stages:
  - test

before_script:
  - apk add go curl
  - go run utils/main.go
  - docker-compose up -d

after_script:
  - docker-compose down -v

unit_tests:
  stage: test
  script:
    - docker-compose exec -T loadbalancer go test ./...
    - docker-compose exec -T supervisor go test ./...
    - docker-compose exec -T storage go test ./...
  only:
    - develop

integration_tests:
  stage: test
  script:
    - ip a
    - cat /etc/hosts
    - sleep 45
    - netstat -a
    - docker-compose logs
    - ./integration/upload.sh
