version: "3.4"
services:
  supervisor:
    build:
      context: ./supervisor
    volumes:
      - ./supervisor:/go/src/supervisor/
    entrypoint: /go/bin/supervisor
    env_file:
      - ./supervisor/.env
    ports:
      - 8080:8080
    networks:
      - loadbalancingnet
      - storenet
  loadbalancer:
    build:
      context: ./loadbalancer
      target: prod
    entrypoint: /go/bin/loadbalancer
    expose:
      - 8081
    env_file:
      - ./loadbalancer/.env
    networks:
      - routingnet
      - loadbalancingnet
      - storenet
  routing_table:
    image: "redis:alpine"
    expose:
      - 6379
    networks:
      - routingnet
  test_routing_table:
    image: "redis:alpine"
    networks:
      - routingnet
  storage:
    build:
      context: ./storage
      target: build
    entrypoint: ./entrypoint.prod.sh
    volumes:
      - ./storage/:/go/src/storage/
      - ./storage/drive:/storage/tmp
    expose:
      - 8082
    env_file:
      - ./storage/.env
    networks:
      - storenet

networks:
  routingnet:
    driver: bridge
  loadbalancingnet:
    driver: bridge
  storenet:
    driver: bridge
