#todo add network configurations 
#Do not expose service that do not require to be exposes (exemple loadbalancer :D)

version: '3.4'
services:
  supervisor: 
    build:
      context: ./supervisor
    volumes: 
      - ./supervisor:/go/src/supervisor/
    entrypoint: CompileDaemon -log-prefix=false -build="go install ./..." -command="/go/bin/supervisor"
    ports: 
      - 8080:8080
  loadbalancer:
    build:
      context: ./loadbalancer
    volumes:
      - ./loadbalancer:/go/src/loadbalancer/
    ports:
      - 8081:8081
    links:
      - routing_table
    environment:
      port: ${LOADBALANCER_PORT}
  routing_table:
    image: "redis:alpine"
    ports:
      - "6379:6379"
