#todo add network configurations
#Do not expose service that do not require to be exposes (exemple loadbalancer :D)

version: "3.4"
services:
  supervisor:
    build:
      context: ./supervisor
    volumes:
      - ./supervisor:/go/src/supervisor/
    entrypoint: CompileDaemon -log-prefix=false -build="go install ./..." -command="/go/bin/supervisor"
    env_file:
      - ./supervisor/.env
    ports:
      - 8080:8080
    networks:
      - loadbalancingnet
      - storenet
  loadbalancer:
    build:
      context: ./loadbalancer
    volumes:
      - ./loadbalancer:/go/src/loadbalancer/
    ports:
      - 8081:8081
    env_file:
      - ./loadbalancer/.env
    networks:
      - routingnet
      - loadbalancingnet
      - storenet
  routing_table:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - routingnet
  storage:
    build:
      context: ./storage
    entrypoint: CompileDaemon -log-prefix=false -build="go install ./..." -command="/go/bin/storage"
    volumes:
      - ./storage/:/go/src/storage/
    ports:
      - 8082:8082
    env_file:
      - ./storage/.env
    networks:
      - storenet

networks:
  routingnet:
    driver: bridge
  loadbalancingnet:
    driver: bridge
  storenet:
    driver: bridge
